TravelTripProje/Controllers/YorumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelTripProje.Models.Sınıflar;

namespace TravelTripProje.Controllers
{
    public class YorumController : Controller
    {
        // GET: Yorum
        Context c = new Context();
        public ActionResult Index()
        {
            var yorumlar = c.Yorumlars.ToList();
            return View(yorumlar);
        }
        public ActionResult YorumSil(int id)
        {
            var b = c.Yorumlars.Find(id);
            c.Yorumlars.Remove(b);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YorumGetir(int id)
        {
            var yr = c.Yorumlars.Find(id);
            return View("YorumGetir", yr);
        }
        public ActionResult YorumGuncelle(Yorumlar y)
        {
            var yrm = c.Yorumlars.Find(y.ID);
            yrm.KullaniciAdi = y.KullaniciAdi;
            yrm.Mail = y.Mail;
            yrm.Yorum = y.Yorum;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

TravelTripProje/Views/Yorum/Index.cshtml
@using TravelTripProje.Models.Sınıflar
@model List<Yorumlar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yorum Listesi</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kullanıcı</th>
        <th>Mail</th>
        <th>Yorum</th>
        <th>Blog</th>
        <th>Sil</th>
        <th>Güncelle</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.KullaniciAdi</td>
            <td>@x.Mail</td>
            <td>@x.Yorum</td>
            <td>@x.Blog.Baslik</td>
            <td><a href="/Yorum/YorumSil/@x.ID" class="btn btn-primary">Sil</a></td>
            <td><a href="/Yorum/YorumGetir/@x.ID" class="btn btn-warning">Güncelle</a></td>
           
        </tr>
    }
</table>

TravelTripProje/Views/Yorum/YorumGetir.cshtml
@model TravelTripProje.Models.Sınıflar.Yorumlar
@{
    ViewBag.Title = "YorumGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Yorum Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("YorumGuncelle", "Yorum", FormMethod.Post))
{
    @Html.LabelFor(x => x.ID)
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control", @readonly = "readonly" })
    <br />

    @Html.LabelFor(x => x.KullaniciAdi)
    @Html.TextBoxFor(x => x.KullaniciAdi, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Mail)
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Yorum)
    @Html.TextAreaFor(x => x.Yorum,15,1, new { @class = "form-control" })
    <br />

    <button class="btn btn-success">Yorum Güncelle</button>
}